name: Bash

on:
  push:
    paths: 
      - lab4.cpp
      - TASKID.txt
      - ALGORITHM.txt
      - .github/workflows/bash.yml
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Test
      shell: bash
      run: |
        alg=0
        if [[ -f ALGORITHM.txt ]]; then alg=$(head -n 1 ALGORITHM.txt); fi
        if [[ $alg -eq 1 ]]; then echo "Running incomplete test suite"; echo "ALGORITHM is "$alg; echo "Grading reduced by 50%"; TERM=xterm-256color bash run_test.sh -- test_TASKID test_build test_algorithm1; elif [[ $alg -eq 2 ]]; then echo "Running incomplete test suite"; echo "ALGORITHM is "$alg; echo "Grading reduced by 50%"; TERM=xterm-256color bash run_test.sh -- test_TASKID test_build test_algorithm2; else TERM=xterm-256color bash run_test.sh; fi
